name: Testing
on: [push, pull_request]
jobs:
  Testing-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        run: ./scripts/test.sh
        shell: bash
  Testing-on-MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        env:
          FASTLANE_EXPLICIT_OPEN_SIMULATOR : "2"
        run: ./scripts/test.sh
        shell: bash
  Testing-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        run: ./scripts/test.sh
        shell: bash
