name: Test on Virtual machine

on:
  - push
  - pull_request

jobs:
  windows:
    name: Windows Server 2022
    runs-on: windows-2022
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run script
        shell: bash
        run: ./scripts/test.sh -d

  ubuntu:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run script
        run: ./scripts/test.sh

  macos:
    name: macOS Big Sur 11
    runs-on: macos-11
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up environment
        run: brew install coreutils
      - name: Run script
        run: ./scripts/test.sh
